var car = 'Honda';
console.log("Is car == 'Honda'? I predict True.");
console.log(car == 'Honda');
var a=5;
console.log('is a<6? True');
console.log(a<6);
var bike ='Suzuki';
console.log('is bike == Suzuki ? True');
console.log(bike=='Suzuki');
var b = 10;
console.log('is b==6? True');
console.log(b==10);
var list=['4','4','4'];
console.log('size array == 3? true');
console.log(list.length==3);
var car = 'Honda';
console.log("Is car != 'Honda'? I predict False.");
console.log(car != 'Honda');
var a=5;
console.log('is a>6? False');
console.log(a>6);
var b = 10;
console.log('is b!=6? False');
console.log(b!=10);
var bike ='Suzuki';
console.log('is bike != Suzuki ? False');
console.log(bike!='Suzuki');
var list=['4','4','4'];
console.log('size array !=3? False');
console.log(list.length>3);